//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beamable.Server.Clients
{
    using System;
    using Beamable.Platform.SDK;
    using Beamable.Server;
    
    
    /// <summary> A generated client for <see cref="Beamable.Microservices.CheckDeviceMicro"/> </summary
    public sealed class CheckDeviceMicroClient : MicroserviceClient, Beamable.Common.IHaveServiceName
    {
        
        public CheckDeviceMicroClient(BeamContext context = null) : 
                base(context)
        {
        }
        
        public string ServiceName
        {
            get
            {
                return "CheckDeviceMicro";
            }
        }
        
        /// <summary>
        /// Call the ValidateDeviceToken method on the CheckDeviceMicro microservice
        /// <see cref="Beamable.Microservices.CheckDeviceMicro.ValidateDeviceToken"/>
        /// </summary>
        public Beamable.Common.Promise<string> ValidateDeviceToken(string deviceCheckToken)
        {
            object raw_deviceCheckToken = deviceCheckToken;
            System.Collections.Generic.Dictionary<string, object> serializedFields = new System.Collections.Generic.Dictionary<string, object>();
            serializedFields.Add("deviceCheckToken", raw_deviceCheckToken);
            return this.Request<string>("CheckDeviceMicro", "ValidateDeviceToken", serializedFields);
        }
    }
    
    internal sealed class MicroserviceParametersCheckDeviceMicroClient
    {
        
        [System.SerializableAttribute()]
        internal sealed class ParameterSystem_String : MicroserviceClientDataWrapper<string>
        {
        }
    }
    
    [BeamContextSystemAttribute()]
    public static class ExtensionsForCheckDeviceMicroClient
    {
        
        [Beamable.Common.Dependencies.RegisterBeamableDependenciesAttribute()]
        public static void RegisterService(Beamable.Common.Dependencies.IDependencyBuilder builder)
        {
            builder.AddScoped<CheckDeviceMicroClient>();
        }
        
        public static CheckDeviceMicroClient CheckDeviceMicro(this Beamable.Server.MicroserviceClients clients)
        {
            return clients.GetClient<CheckDeviceMicroClient>();
        }
    }
}
