//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beamable.Server.Clients
{
    using System;
    using Beamable.Platform.SDK;
    using Beamable.Server;
    
    
    /// <summary> A generated client for <see cref="Beamable.Microservices.DeviceCheckMicroservice"/> </summary
    public sealed class DeviceCheckMicroserviceClient : MicroserviceClient, Beamable.Common.IHaveServiceName
    {
        
        public DeviceCheckMicroserviceClient(BeamContext context = null) : 
                base(context)
        {
        }
        
        public string ServiceName
        {
            get
            {
                return "DeviceCheckMicroservice";
            }
        }
        
        /// <summary>
        /// Call the SendToServer method on the DeviceCheckMicroservice microservice
        /// <see cref="Beamable.Microservices.DeviceCheckMicroservice.SendToServer"/>
        /// </summary>
        public Beamable.Common.Promise<string> SendToServer(string deviceCheckToken)
        {
            object raw_deviceCheckToken = deviceCheckToken;
            System.Collections.Generic.Dictionary<string, object> serializedFields = new System.Collections.Generic.Dictionary<string, object>();
            serializedFields.Add("deviceCheckToken", raw_deviceCheckToken);
            return this.Request<string>("DeviceCheckMicroservice", "SendToServer", serializedFields);
        }
    }
    
    internal sealed class MicroserviceParametersDeviceCheckMicroserviceClient
    {
        
        [System.SerializableAttribute()]
        internal sealed class ParameterSystem_String : MicroserviceClientDataWrapper<string>
        {
        }
    }
    
    [BeamContextSystemAttribute()]
    public static class ExtensionsForDeviceCheckMicroserviceClient
    {
        
        [Beamable.Common.Dependencies.RegisterBeamableDependenciesAttribute()]
        public static void RegisterService(Beamable.Common.Dependencies.IDependencyBuilder builder)
        {
            builder.AddScoped<DeviceCheckMicroserviceClient>();
        }
        
        public static DeviceCheckMicroserviceClient DeviceCheckMicroservice(this Beamable.Server.MicroserviceClients clients)
        {
            return clients.GetClient<DeviceCheckMicroserviceClient>();
        }
    }
}
