//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beamable.Server
{
    using Beamable.Microservices;
    using Beamable.Common;
    
    
    public class Program
    {
        
        public static System.Threading.Tasks.Task<int> Main(string[] args)
        {
            return global::Beamable.Server.CommandLine<Beamable.Microservices.DeviceCheckMicroservice>.Main(args);
        }
    }
}
